Improve pre-push commands

diff --git a/.husky/pre-push b/.husky/pre-push
--- a/.husky/pre-push
+++ b/.husky/pre-push
@@ -1,13 +1,22 @@
 #!/usr/bin/env sh
+set -e
 . "$(dirname -- "$0")/_/husky.sh"
 
+read local_ref local_sha remote_ref remote_sha
+REMOTE_BRANCH=${remote_ref#refs/heads/}
 BRANCH=$(git symbolic-ref --short HEAD)
 
-if [ "$BRANCH" = "main" ] || [ "$BRANCH" = "develop" ]; then
-  echo "🔍 Running build check on branch: $BRANCH"
+if [ "$REMOTE_BRANCH" = "main" ] || [ "$REMOTE_BRANCH" = "develop" ]; then
+  echo "‼️ Pushing directly to '$REMOTE_BRANCH' ‼️"
+  echo "⏺️ Running build command..."
   npm run build
 else
-  echo "⏭️ Skipping build check on branch: $BRANCH"
+  if echo "$BRANCH" | grep -Eq '^(feature|fix|improvement|hotfix|chore|refactor|test|docs)/'; then
+    echo "✅ Branch name '$BRANCH' is valid."
+    echo "⏭️ Skipping build check on branch: $BRANCH"
+  else
+    echo "❌ Invalid branch name: '$BRANCH'"
+    echo "🔒 Branch must start with one of: feature/, fix/, improvement/, hotfix/, chore/, refactor/, test/, docs/"
+    exit 1
+  fi
 fi
-
-npm run build
