Feature/add branch protection gh action (#10)
* Add branch protection GH actions

* Trigger CI

* Trigger CI

diff --git a/.husky/pre-push b/.husky/pre-push
--- a/.husky/pre-push
+++ b/.husky/pre-push
@@ -6,25 +6,19 @@ read local_ref local_sha remote_ref remote_sha
 REMOTE_BRANCH=${remote_ref#refs/heads/}
 BRANCH=$(git symbolic-ref --short HEAD)
 
-if [ "$REMOTE_BRANCH" = "main" ]; then
-  echo "❌ Pushing directly to '$REMOTE_BRANCH' is NOT allowed! Please merge 'develop' or create new hotfix/ branch."
+if [ "$REMOTE_BRANCH" = "main" ] || [ "$REMOTE_BRANCH" = "develop" ]; then
+  echo "❌ Pushing directly to '$REMOTE_BRANCH' is NOT allowed!"
   exit 1
 fi
-if [ "$REMOTE_BRANCH" = "develop" ]; then
-  echo "‼️ Pushing directly to '$REMOTE_BRANCH' - this push may get rejected by GH ‼️"
+
+if echo "$BRANCH" | grep -Eq '^(feature|fix|improvement|hotfix|release|refactor|test|docs|chore)/'; then
+  echo "✅ Branch name '$BRANCH' is valid."
   echo "🟠 Running tests..."
   npm test
   echo "⏺️ Running build command..."
   npm run build
 else
-  if echo "$BRANCH" | grep -Eq '^(feature|fix|improvement|hotfix|chore|refactor|test|docs)/'; then
-    echo "✅ Branch name '$BRANCH' is valid."
-    echo "🟠 Running tests..."
-    npm test
-    echo "⏭️ Skipping build check on branch: $BRANCH"
-  else
-    echo "❌ Invalid branch name: '$BRANCH'"
-    echo "🔒 Branch must start with one of: feature/, fix/, improvement/, hotfix/, chore/, refactor/, test/, docs/"
-    exit 1
-  fi
+  echo "❌ Invalid branch name: '$BRANCH'"
+  echo "🔒 Branch must start with one of: feature/, fix/, improvement/, hotfix/, release/, refactor/, test/, docs/, chore/"
+  exit 1
 fi
