Release/1.0.2 (#16)
* Automate Vercel Prod Deploy (#12)

* Expand deploy GH action with creating tag automatically (#13)

* Update pre-push

* Release 1.0.2

diff --git a/.husky/pre-push b/.husky/pre-push
--- a/.husky/pre-push
+++ b/.husky/pre-push
@@ -5,7 +5,7 @@ set -e
 read local_ref local_sha remote_ref remote_sha
 BRANCH=$(git symbolic-ref --short HEAD)
 
-if [ "$BRANCH" = "main" ] || [ "$BRANCH" = "develop" ]; then
+if [ "$BRANCH" = "main" ]; then
   echo "❌ Pushing directly to '$REMOTE_BRANCH' is NOT allowed!"
   exit 1
 else
@@ -19,8 +19,10 @@ else
       fi
     fi
   else
-    echo "❌ Invalid branch name: '$BRANCH'"
-    echo "🔒 Branch must start with one of: feature/, fix/, improvement/, hotfix/, release/, refactor/, test/, docs/, chore/"
-    exit 1
+    if [ "$BRANCH" != "develop" ]; then
+      echo "❌ Invalid branch name: '$BRANCH'"
+      echo "🔒 Branch must start with one of: feature/, fix/, improvement/, hotfix/, release/, refactor/, test/, docs/, chore/"
+      exit 1
+    fi
   fi
 fi
